
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x08u]\xcc"kT\xee\xcc\xd2\x85o:\xee\xf5\xfd'
    
_lr_action_items = {'COMMA':([9,12,21,22,23,],[14,14,14,14,14,]),'LBRACE':([8,9,10,11,12,13,15,16,20,21,22,23,25,26,27,],[-1,-1,19,-10,-1,-9,-8,-14,-7,-1,-1,-1,-13,-11,-12,]),'COLON':([6,],[8,]),'BIGLIST':([0,1,2,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,25,26,27,28,],[2,2,-6,-1,-1,-1,-10,-1,-9,-8,-14,-5,-16,2,-7,-1,-1,-1,-13,-11,-12,-15,]),'num':([8,14,],[9,23,]),'RBRACE':([1,2,4,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,],[-1,-6,-4,-3,-1,-1,-1,-10,-1,-9,-8,-14,-5,-16,-1,-7,-1,-1,-1,28,-13,-11,-12,-15,]),'specialkeyword':([8,14,],[13,21,]),'string':([8,14,],[12,22,]),'id':([0,1,2,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,25,26,27,28,],[6,6,-6,-1,-1,-1,-10,-1,-9,-8,-14,-5,-16,6,-7,-1,-1,-1,-13,-11,-12,-15,]),'$end':([0,1,2,3,4,5,7,8,9,10,11,12,13,15,16,17,18,20,21,22,23,25,26,27,28,],[-1,-1,-6,-2,-4,0,-3,-1,-1,-1,-10,-1,-9,-8,-14,-5,-16,-7,-1,-1,-1,-13,-11,-12,-15,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'OptionalBraceBlock':([10,],[17,]),'Definition':([0,1,19,],[1,1,1,]),'OptionalThings':([8,],[10,]),'OptionalThings2':([9,12,21,22,23,],[15,20,25,26,27,]),'DefList':([0,1,19,],[3,7,24,]),'epsilon':([0,1,8,9,10,12,19,21,22,23,],[4,4,11,16,18,16,4,16,16,16,]),'S':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',75),
  ('S -> DefList','S',1,'p_S','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',84),
  ('DefList -> Definition DefList','DefList',2,'p_DefList','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',88),
  ('DefList -> epsilon','DefList',1,'p_DefList','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',89),
  ('Definition -> id COLON OptionalThings OptionalBraceBlock','Definition',4,'p_Definition','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',102),
  ('Definition -> BIGLIST','Definition',1,'p_Definition2','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',112),
  ('OptionalThings -> string OptionalThings2','OptionalThings',2,'p_OptionalThings','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',122),
  ('OptionalThings -> num OptionalThings2','OptionalThings',2,'p_OptionalThings','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',123),
  ('OptionalThings -> specialkeyword','OptionalThings',1,'p_OptionalThings','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',124),
  ('OptionalThings -> epsilon','OptionalThings',1,'p_OptionalThings','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',125),
  ('OptionalThings2 -> COMMA string OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',134),
  ('OptionalThings2 -> COMMA num OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',135),
  ('OptionalThings2 -> COMMA specialkeyword OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',136),
  ('OptionalThings2 -> epsilon','OptionalThings2',1,'p_OptionalThings2','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',137),
  ('OptionalBraceBlock -> LBRACE DefList RBRACE','OptionalBraceBlock',3,'p_OptionalBraceBlock','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',146),
  ('OptionalBraceBlock -> epsilon','OptionalBraceBlock',1,'p_OptionalBraceBlock','C:\\Users\\ajart\\School\\Spring 2016\\Graphics 2\\Animal Bowling\\basic-framework\\assets\\Models\\parsefbx.py',147),
]
